import { Body, Controller, Post, Req, Res } from '@nestjs/common';
import {
  ApiBasicAuth,
  ApiBody,
  ApiConsumes,
  ApiOkResponse,
  ApiOperation,
  ApiResponse,
  ApiTags,
} from '@nestjs/swagger';
import type { Request, Response } from 'express';
import { TokenRequestError } from './token-request.error';
import { TokenService } from './token.service';

@Controller()
@ApiTags('Token')
export class TokenController {
  constructor(private readonly tokenService: TokenService) {}

  @Post('token')
  @ApiOperation({
    summary: 'Exchange a one-time authorization code for an access token',
    description:
      'Back-channel endpoint for confidential application backends. It validates Basic client credentials, exact redirect URI, PKCE verifier, code expiry/replay, user, application, and central session.',
  })
  @ApiBasicAuth('clientCredentials')
  @ApiConsumes('application/x-www-form-urlencoded')
  @ApiBody({
    schema: {
      type: 'object',
      required: ['grant_type', 'code', 'redirect_uri', 'code_verifier'],
      properties: {
        grant_type: {
          type: 'string',
          enum: ['authorization_code'],
          example: 'authorization_code',
        },
        code: {
          type: 'string',
          description:
            'Short-lived authorization code received by the callback.',
          example: 'replace-with-one-time-authorization-code',
        },
        redirect_uri: {
          type: 'string',
          format: 'uri',
          example: 'http://localhost:3002/auth/callback',
        },
        code_verifier: {
          type: 'string',
          description: 'Original PKCE verifier generated by the application.',
          example: 'replace-with-pkce-code-verifier-at-least-43-characters',
        },
      },
    },
  })
  @ApiOkResponse({
    description:
      'Opaque Bearer token. The response is no-store and the raw token is returned only once.',
    schema: {
      example: {
        access_token: 'replace-with-opaque-access-token',
        token_type: 'Bearer',
        expires_in: 900,
        scope: 'profile',
      },
    },
  })
  @ApiResponse({
    status: 400,
    description:
      'OAuth invalid_request, invalid_grant, or unsupported_grant_type response.',
  })
  @ApiResponse({
    status: 401,
    description:
      'OAuth invalid_client response with WWW-Authenticate Basic challenge.',
  })
  async exchange(
    @Body() body: Record<string, unknown>,
    @Req() request: Request,
    @Res() response: Response,
  ): Promise<void> {
    response.set({
      'Cache-Control': 'no-store',
      Pragma: 'no-cache',
    });

    try {
      if (!request.is('application/x-www-form-urlencoded')) {
        throw new TokenRequestError(
          'invalid_request',
          'Content-Type harus application/x-www-form-urlencoded',
        );
      }

      const result = await this.tokenService.exchange(
        {
          grantType: body['grant_type'],
          code: body['code'],
          redirectUri: body['redirect_uri'],
          codeVerifier: body['code_verifier'],
        },
        request.get('authorization'),
        { ipAddress: request.ip?.slice(0, 45) },
      );

      response.status(200).json({
        access_token: result.accessToken,
        token_type: result.tokenType,
        expires_in: result.expiresIn,
        scope: result.scope,
      });
    } catch (error: unknown) {
      if (!(error instanceof TokenRequestError)) {
        throw error;
      }

      if (error.code === 'invalid_client') {
        response.set('WWW-Authenticate', 'Basic realm="token"');
      }

      response.status(error.statusCode).json({
        error: error.code,
        error_description: error.message,
      });
    }
  }
}
